name: example
description: "A new Flutter project."
publish_to: "none" #
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2

  local_first:
    path: ../

  redis: ^4.0.0
  mongo_dart: ^0.10.0
  awesome_task_manager: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
