name: local_first_hive_storage
description: "Hive adapter for local_first: schema-less, offline-first storage with Hive boxes and metadata support."
version: 0.2.0
repository: https://github.com/rafaelsetragni/local_first
issue_tracker: https://github.com/rafaelsetragni/local_first/issues

resolution: workspace

environment:
  sdk: ^3.10.0
  flutter: ">=1.17.0"

topics:
  - local-first
  - hive
  - storage

dependencies:
  flutter:
    sdk: flutter
  local_first: ^0.5.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.3
