name: local_first_shared_counter_example
description: "Shared preferences-backed LocalFirst counter example."
publish_to: "none" #
version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2

  local_first:
    path: ../../local_first
  local_first_shared_preferences:
    path: ../
  local_first_hive_storage:
    path: ../../local_first_hive_storage
  local_first_websocket:
    path: ../../local_first_websocket
  http: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

dependency_overrides:
  local_first:
    path: ../../local_first
flutter:
  uses-material-design: true
